name: Test terraform modules
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Checkout reusable workflow dir
        uses: actions/checkout@v4
        with:
          repository: wearetechnative/reusable_workflow_terraform
          #token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: reusable-workflow-repo


      - name: run the bash script          
        run: ${GITHUB_WORKSPACE}/reusable-workflow-repo/module_checker.sh
